services:
  filesystem:
    image: seppaleinen/mcp-filesystem:latest
    build:
      context: filesystem
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64

  helmfile:
    image: seppaleinen/mcp-helmfile:latest
    build:
      context: helmfile
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
